# Generated by Django 4.1.6 on 2023-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
